#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit.sample".

#npm run lint:fix
#npm run lint

#ESLINT_RESULT="$?"

#if [[ "${ESLINT_RESULT}" == 0 ]]; then
  #printf "\n\033[34;40mUPDATE PACKAGE's VERSION\033[0m\n"
#else
  #printf "\n\031[40mLINT FAILED:\033[0m\n fix linting error first and try again"
  #exit 1
#fi
