export const PROTOCOL_VERSION = 14;
export const ARTNET_PACKET_ID = 'Art-Net'
export const ARTNET_PORT = 6454
export const DEFAULT_POLL_INTERVAL = 5000
export const NODE_DEATH_TIMEOUT_MS = 10000
export const DEFAULT_NODE_WATCHER_INTERVAL_MS = 3000
export const DEFAULT_NETWORK = '0.0.0.0'
export const DEFAULT_NETMASK = '0.0.0.0'

export enum OP_CODE {
    POLL = 0x2000,
    POLL_REPLY = 0x2100,
    DIAG_DATA = 0x2300,
    DMX = 0x5000,
    SYNC = 0x5200,
}

export enum DISCOVERY_EVENT {
    NODE_STATUS_UPDATE = 'NODE_STATUS_UPDATE',
    NEW_NODE_REGISTERED = 'NEW_NODE_REGISTERED',
    NODE_IS_DEAD = 'NODE_IS_DEAD',
}

export enum NETWORK_COMMUNICATOR_EVENTS {
    ART_NET_PACKET = 'ART_NET_PACKET'
}

export enum DISCOVERY_STATUS {
    RUNNING = 'RUNNING',
    SUSPENDED = 'SUSPENDED'
}

export enum ARTNET_ERROR_CODE {
    WRONG_ACTION = 'WRONG_ACTION',
    SOCKET_ERROR = 'SOCKET_ERROR',
    DEVICE_DRIVER_NOT_FOUND = 'DEVICE_DRIVER_NOT_FOUND',
    NODE_NOT_FOUND = 'NODE_NOT_FOUND',
    NODE_NOT_SUBSCRIBED = 'NODE_NOT_SUBSCRIBED',
    CORRUPTER_PACKET = 'CORRUPTER_PACKET',
}