name: npm-publish
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: 21
      - name: Installing monorepo npm packages
        run: npm install --workspace=packages
      - name: Installing other npm packages
        run: npm install
      - name: Linting
        run: npm run lint
      - name: Building ArtNet
        run: npm run build
  npm-publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: 21
          registry-url: https://registry.npmjs.org/
      - name: Installing monorepo npm packages
        run: npm install --workspace=packages
      - name: Installing other npm packages
        run: npm install
      - name: Building ArtNet
        run: npm run build
      - name: Publishing
        run: npm publish --workspace=packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm}}
