name: TEST
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: 21
      - name: Installing monorepo npm packages
        run: npm install --workspace=packages
      - name: Installing other npm packages
        run: npm install
      - name: Linting
        run: npm run lint
      - name: Building ArtNet
        run: npm run build

